service: filler-text

plugins:
- serverless-webpack
- "@kalarrs/serverless-local-dev-server"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  memorySize: 128
  environment:
#    CHANGE_VALUE: ${env:CHANGE_VALUE, file(../serverless.yml):provider.environment.CHANGE_VALUE}

functions:
  handler:
    handler: src/handler.fillerText
    events:
    - http:
        path: filler-text
        method: post
        cors: true

custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
